FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

COPY dependency/requirements.txt dependency/
RUN pip install --no-cache-dir -r dependency/requirements.txt

COPY . /app

CMD ["python", "main.py"]
